[window]
decorations = "buttonless"
startup_mode = "Maximized"
opacity = 0.95
padding = { x = 8, y = 8 }

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
size = 13.0

[cursor]
style = { shape = "Beam", blinking = "On" }

[colors.primary]
background = "#1E1E1E"
foreground = "#D4D4D4"

[colors.normal]
black = "#1E1E1E"
red = "#F44747"
green = "#608B4E"
yellow = "#DCDCAA"
blue = "#569CD6"
magenta = "#C586C0"
cyan = "#4EC9B0"
white = "#D4D4D4"

[scrolling]
history = 10000

[keyboard]
bindings = [
  # Option + Arrow = move by word
  { key = "Left",  mods = "Alt",  chars = "\u001bb" },
  { key = "Right", mods = "Alt",  chars = "\u001bf" },

  # Command + Arrow = move to start/end of line
  { key = "Left",  mods = "Command", chars = "\u001bOH" },
  { key = "Right", mods = "Command", chars = "\u001bOF" },

  { key = "Backspace", mods = "Command", chars = "\u0015" }  # sends Ctrl+U
]
